version: "3"

services:
  db:
    image: "postgres"
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "registrado"
    ports:
      - "5432:5432"
    volumes: 
      - db:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/registrado?schema=public"
    restart: always
    volumes:
      - ./backend:/app
    command: npm run dev
    depends_on:
      - db

  frontend:
    build: ./frontend
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - API_URL=http://localhost:3001/
      - NODE_ENV=dev
    restart: always
    depends_on:
      - backend

volumes:
  db:
    driver: local
