import type { NextPage, GetServerSideProps } from 'next';
import Head from 'next/head';
import styles from '../styles/styles.module.scss';

const Home: NextPage = () => {
  return (
    <div className={ styles.container }>
      <Head>
        <title>Registrado</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={ styles.main }>
        <header className={ styles.header }>
          <div className={ styles.headerContainer }>
            <h1 className={ styles.title }>
              Registrado
            </h1>
          </div>
        </header>

        <section className={ styles.containerLoading }>
          <div className={ styles.ldsRipple }>
            <div></div>
            <div></div>
          </div>
        </section>
      </main>
    </div>
  )
}

export const getServerSideProps: GetServerSideProps = async () => {
  const res = await fetch('http://localhost:3001/users')
  const users = await res.json()

  console.log(users);

  return {
    props: { users },
  }
}

export default Home;
