import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.scss'

const Home: NextPage = () => {
  return (
    <div className={ styles.container }>
      <Head>
        <title>Registrado</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={ styles.main }>
        <header className={ styles.header }>
          <div className={ styles.headerContainer }>
            <h1 className={ styles.title }>
              Registrado
            </h1>
          </div>
        </header>
      </main>
    </div>
  )
}

export default Home;
