name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-back:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "registrado-backend"
          heroku_email: "adilsongb.rabelo@gmail.com"
          usedocker: true
          appdir: "backend"
  build-front:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "registrado-frontend"
          heroku_email: "adilsongb.rabelo@gmail.com"
          usedocker: true
          appdir: "frontend"